// Code generated by ifacemaker; DO NOT EDIT.

package controller

import (
	"context"

	"github.com/wtkeqrf0/restService/internal/enricher"
)

// Controller describes methods, implemented by the enricher package.
type Enricher interface {
	// EnrichFIO sends requests to enrich the FIO structure.
	// The method expects the context (ctx) and the full user name (FIO).
	//
	// Eventually the FIOEnriched structure is returned.
	//
	// If FIO is incorrect, all new fields will have zero values.
	EnrichFIO(ctx context.Context, fio enricher.FIO) (resp enricher.EnrichedFIO, err error)
	// ValidateName on exist. Accepts name
	// and returns true, if name can be enriched.
	ValidateName(name string) bool
}
