version: '3.9'

services:
  postgres:
    platform: linux/amd64
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: "em_service"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  redis:
    platform: linux/amd64
    image: redis:7.2.1-alpine3.18
    command: >
      --requirepass 1234
    ports:
      - "6379:6379"

  zookeeper:
    platform: linux/amd64
    image: zookeeper:3.9.0
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - '29092:29092'
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper