// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EnrichedFio is the predicate function for enrichedfio builders.
type EnrichedFio func(*sql.Selector)
