// Code generated by ifacemaker; DO NOT EDIT.

package controller

import (
	"context"
)

// Controller describes methods, implemented by the redis package.
type Redis interface {
	// Save `ret` by key. Key must be cached by func CacheKey.
	Save(ctx context.Context, key string, ret any) error
	// Get data of type `want` by `key`.
	//
	// Key must be cached by func CacheKey. `want` must be a pointer.
	Get(ctx context.Context, key string, want any) error
	CacheKey(obj any) (string, error)
	Close() error
}
