// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EnrichedFiosColumns holds the columns for the "enriched_fios" table.
	EnrichedFiosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "surname", Type: field.TypeString},
		{Name: "patronymic", Type: field.TypeString, Nullable: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "gender", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
	}
	// EnrichedFiosTable holds the schema information for the "enriched_fios" table.
	EnrichedFiosTable = &schema.Table{
		Name:       "enriched_fios",
		Columns:    EnrichedFiosColumns,
		PrimaryKey: []*schema.Column{EnrichedFiosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EnrichedFiosTable,
	}
)

func init() {
}
