// Code generated by ifacemaker; DO NOT EDIT.

package controller

import (
	"context"

	ce "github.com/wtkeqrf0/restService/internal/enricher/controller"
	"github.com/wtkeqrf0/restService/internal/kafka"
	cp "github.com/wtkeqrf0/restService/internal/postgres/controller"
)

// Controller describes methods, implemented by the kafka package.
type Kafka interface {
	// Produce creates a new kafka message.
	// When field `cause` is `nil`, message will be `success` status.
	Produce(ctx context.Context, fio kafka.FIO, causes map[string]string) (err error)
	// Consume starts to consume messages from topics `FIO` and `FIO_FAILED`.
	//
	// Method doesn't block the main goroutine.
	Consume(ctx context.Context, db cp.Postgres, enr ce.Enricher)
}
